### ISSUE TITLE
PR #6 shouldn't have been merged so quickly

### ISSUE THREAD

**Issue by cdcapano** [gwastro/gwin#7]
I was in the midst of writing a review on #6 when it was merged... since the PR was merged, I can't submit my review any more. I don't want to revert it, so sticking my requests here to be addressed in another PR.

Some requests in CONTRIBUTING.md:

 * Line 37: Remove the `cd lalsuite`. Also, could we suggest calling the upstream gwastro instead? This is a matter of personal taste, but I like to always use the names of the organizations/users from which I've forked a repo.
 * Line 54: Add a `get fetch upstream` (or `gwastro`, if you agree with my previous comment) here, before the checkout, to ensure people know that they need to do a fetch first to branch off the most recent changes.

For the CODEOWNERS... is it the case that a code owner *must* approve any PR on that file, or only that they are automatically added as *a* reviewer, with the possibility that a reviewee could request (and get approval from) another reviewer in addition? I'm fine with it if the latter. But if the former, I'd need some convincing... that seems a bit draconian. We'd really need some way of determining who should be added as new code owners, since a file could change substantially over time.

For an initial set of code owners, I'd use the people listed in the copy right notices at the top of all the files. We can have multiple people listed for a file, correct?

**Comment by duncanmmacleod** [comment]
> Some requests in CONTRIBUTING.md:
>
> - Line 37: Remove the cd lalsuite. Also, could we suggest calling the upstream gwastro instead? This is a matter of personal taste, but I like to always use the names of the organizations/users from which I've forked a repo.

I like the idea of calling the upstream remote `gwastro`, so can make that change.

> - Line 54: Add a get fetch upstream (or gwastro, if you agree with my previous comment) here, before the checkout, to ensure people know that they need to do a fetch first to branch off the most recent changes.

The `git fetch upstream` command is included on line 44. Perhaps your point is to double-check-make-sure-always fetch upstream before you create a new branch?

I will open a PR for contributing to address these concerns.

> For the CODEOWNERS... is it the case that a code owner must approve any PR on that file, or only that they are automatically added as a reviewer, with the possibility that a reviewee could request (and get approval from) another reviewer in addition? I'm fine with it if the latter. But if the former, I'd need some convincing... that seems a bit draconian.

My understanding is that the documented code owner is just the default reviewer for PRs including changes to one of their files. We can then remove that person if they are unavailable or an inappropriate choice in some way.

> We'd really need some way of determining who should be added as new code owners, since a file could change substantially over time.

This would have to be a manual process, perhaps just prompted by new PRs for a given code. I can imagine someone posting a PR that changes code that you own, and you suggest a different reviewer, which should prompt us to update the `CODEOWNERS` file.

> For an initial set of code owners, I'd use the people listed in the copy right notices at the top of all the files. We can have multiple people listed for a file, correct?

Yes, definitely. I can open a PR that manually adds the copyright owners for each file.

**Comment by cdcapano** [comment]
Ok, that sounds better for the code owners. Do you know if github will still offer suggested reviewers if a file has a code owner? I've found their suggested reviewers to work really well, as it seems smart enough to figure out who's edited what section of code overtime and thus who is best to review it.

However, I do like the sounds of the code owners as a notification system. It's happened to me a few times where a change was made to piece of code I was interested in without me knowing because I wasn't picked to review it. (Yes, I get emails for everything, but I set up filters to only get the ones I'm involved.) This sounds like a way for people to at least get an email notifying them that a change is being made to code they care about.

**Comment by vivienr** [comment]
And github does still offer suggested reviewers. It's just that the code owner gets assigned not matter what. So yes, it does work as a notification system, including for people who may not be suggested reviewers, or from merge requests where contributors have a reason to ignore the suggested reviewer.
